name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install dependencies
        run: uv sync --frozen
      
      - name: Run ruff linting
        run: uv run ruff check .
      
      - name: Check ruff formatting
        run: uv run ruff format --check .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install dependencies
        run: uv sync --frozen
      
      - name: Run tests
        run: uv run pytest -v

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install dependencies
        run: uv sync --frozen
      
      - name: Test action with valid organization file
        run: |
          mkdir -p test-organizations
          cp tests/fixtures/valid_org.yaml test-organizations/test-org.yaml
          uv run python validate.py \
            --files "test-organizations/test-org.yaml" \
            --organizations-dir "test-organizations" \
            --slug-field "adres"
      
      - name: Test action with invalid organization file (should fail)
        run: |
          cp tests/fixtures/invalid_krs.yaml test-organizations/invalid-org.yaml
          if uv run python validate.py \
            --files "test-organizations/invalid-org.yaml" \
            --organizations-dir "test-organizations" \
            --slug-field "adres"; then
            echo "Expected validation to fail but it passed"
            exit 1
          else
            echo "Validation correctly failed for invalid file"
          fi
